### PR TITLE
Issue#78 test cases for post get additional info

### LINKED ISSUE #78: Dev: Test cases for POST and GET /user/additional_info
## Description
As a student,
I need write test cases for POST and GET /user/additional_info api endpoints,
so that I can ensure the code quality of the project.

## Mocks
NA

### Update [Required]
- [ ] for successful POST /user/additional_info with response 201 - Created
- [ ] for successful GET /user/additional_info with response 200 - Ok
- [ ] for each POST and GET, write tests for any of the 40x responses (such as 400 - Bad request, 404 - Not Found, 409 - Conflict, etc) and 500 Internal server error

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Additional note**
This issue is a part of issue #62 (Create/update user profile) and #63  (Get user profile)

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
Add test cases for POST and GET /user/additional_info

Fixes #78 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
- run tests on VS Code test explorer - result: all tests passed

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
Update @ramitsawhney27 and @anitab-org/bridgeintech-maintainers. Here're the test cases for POST and GET /user/additional_info functionality (PR #77 ). Look forward to your feedback.

**Review by ramitsawhney27 — DISMISSED** [review]

**Review by foongminwong — DISMISSED** [review]

**Comment by foongminwong** [comment]
hey @mtreacy002 , can you resolve the conflicting files?

**Comment by mtreacy002** [comment]
@foongminwong . Done. I've fixed the merge conflict. Can you please review? Thanks.
@ramitsawhney27 , your approval got removed by the latest force pushed for resolving merge conflict. Can you please re-approve? Thanks

**Review by ramitsawhney27 — DISMISSED** [review]

**Review by foongminwong — DISMISSED** [review]
Reviewed, ran tests locally & successfully

test-pr-79

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've made the requested changes as per discussion in the BIT meeting (timezone value). Please check it out

**Comment by mtreacy002** [comment]
Update @isabelcosta and @anitab-org/bridgeintech-maintainers . I've solved the merge conflict on this one. Please check and approve when you have time, thanks.

**Review by foongminwong — APPROVED** [review]

**Review by isabelcosta — APPROVED** [review]
Great work @mtreacy002 💪

**Pull request merged**
