### PR TITLE
HTTP code added

### LINKED ISSUE #183: Use HTTPStatus code values instead of enum representation in Organisations API
**Describe the bug**

The values shown on Swagger UI of Users API should be in number format instead of Enum Representations of Status Codes. For example 200 instead of HTTPStatus.OK. 

**To Reproduce**

1. Go to https://bridgeintech-bit-heroku-psql.herokuapp.com/
2. Scroll down to ```Organisations Api```
3. See enum representation.

image

**Expected behavior**
Use of Values of Status Codes instead of Enum Representations in Swagger UI

**Desktop (please complete the following information):**
 - OS: Ubuntu 20+
 - Browser FireFox Web Browser
 - Version --

### PR DESCRIPTION
**Pull request by shades-7**
### Description

Used HTTPStatus code values instead of enum representation in Organisations API

Fixes #183

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
-

### How Has This Been Tested?
Screenshot from 2021-03-22 22-29-22

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by epicadk — APPROVED** [review]
💯 thankyou for your contribution : ).

**Review by Rahulm2310 — APPROVED** [review]
Looks perfect 🎉. @shades-7 Thanks for your contribution.
@mtreacy002  As we have 2 approvals, adding `ready to merge` label.

**Comment by mtreacy002** [comment]
@Rahulm2310 , I change the label to `Needs testing` 😉

**Review by mtreacy002 — APPROVED** [review]
Good job, @shades-7 . 
I've tested the pr locally and below is the test summary:
1. Code review: Done - received 2 approvals
2. All possible outcome were tested.
    Expected behaviour: all api endpoints should show HTTPStatus in numeric values instead of enum representation.
    Actual behaviour: as expected (see gif below)
ezgif com-gif-maker (42)
3. Environment:
    * OS: MacOS Catalina 10.15.7
    * Browser: Safari 14.0.2

Thank you again for contributing to the project @shades-7 🎉🎉🎉

**Pull request merged**
