### PR TITLE
Test: Issue66 User Login API test cases

### LINKED ISSUE #66: Test: write test cases for Login user API
## Description
As a student,
I need test login user functionality,
so that I can make sure the functionality works as expected.

## Mocks
NA

### Update [Required]
- [ ] test by mocking API when user successfully login (success response 200)
- [ ] test by mocking API when wrong password or username is given (error code 401)
- [ ] test by mocking API when internal server error is returned (error code 500)

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description

Add test cases for User Login API endpoints

Fixes #66 

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

run test explorer -> result: pass
run python -m unittest discover tests -> reesultt: pass

Screen Shot 2020-07-06 at 12 14 35 am

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
Update: @anitab-org/bridgeintech-maintainers . Here's the WIP for Login user API test cases. You noticed that Travis build is failed. I need to troubleshoot this bug as you can see in gif link on the PR description, if I run tests as a whole form Test Explorer in VS Code, it will fail, but if I target just the fail test it will pass. I'm not sure why. Any hint will help, Thanks.

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've managed to solve the bug issue on successful login api. My guess is correct that the MagicMock objects cannot be passed to different function outside its original function where the patch is declared (at least that's my conclusion for now). I've pushed the fix and it passes travis. So this PR is now complete. Please provide your review. Thanks

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've just fixed merge conflict on this PR. Can you please give review this PR?

**Review by foongminwong — APPROVED** [review]

**Comment by mtreacy002** [comment]
Thanks, @foongminwong for your approval. @ramitsawhney27 or @isabelcosta . Can I also have your approval on this? This PR was the one we troubleshoot together in our BIT weekly meeting last week. The issue I had last week just because of I tried to separate the codes to mini functionalities. Now that I've put them all together just as per what I've done on Register test cases, it works. 

Since you already approved this verbally last week, can you please approve and merge it now since I will start working on GET /user profile today. It'll be good to have this PR code already merged to develop before I start working on a new PR branch (saves me from merge conflict later on). Thanks for your support.

**Review by ramitsawhney27 — APPROVED** [review]

**Comment by mtreacy002** [comment]
Thanks, @ramitsawhney27 for the approval. can you also please merge this PR?

**Pull request merged**
