### PR TITLE
chore : added black and black's github action to format the code

### LINKED ISSUE #184: Setup black formatter and it's github action
**Is your feature request related to a problem? Please describe.**
As a developer, I need to have good, structured, readable code to be able to read through it painlessly and effortlessly.

**Describe the solution you'd like**
The idea is to run Black through a single pass, and then integrate the [official GitHub action](https://github.com/psf/black#github-actions) so that we make it a habit for every developer to run black before committing their code.

### PR DESCRIPTION
**Pull request by vj-codes**
### Description
Added black and black's github action to format the code and also reformatted the existing code.

Fixes #184 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
gh action for black has been tested on my fork where it passed successfully 
https://github.com/vj-codes/bridge-in-tech-backend/actions

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vj-codes** [comment]
@mtreacy002 @isabelcosta hey can you please review this PR? Thanks 😉 
Also should some info be added in readme?And should black be added in requirements.txt?

**Comment by mtreacy002** [comment]
@vj-codes, just curious. I noticed that Travis didn't get built for this PR. Does this mean we also need to write a GitHub workflow for the test cases?

**Comment by vj-codes** [comment]
@mtreacy002 yeah you suggested to make it into 2 issues that's why I didn't add Travis here. 
I've created another issue for travis as well.

**Comment by mtreacy002** [comment]
> Also should some info be added in readme?And should black be added in requirements.txt?

Yep, I think we need to mention on Readme that we're using the black formatter for code formatter. It'll be good if there's a tag we can add a tag for this.

On adding it to the requirements.txt, I think since the formatter itself gets triggered in github action, we don't need to place it in requirements.txt as dependencies. 

Also, @vj-codes, since we have Travis move to Github action on different issue (#192), we should put this PR on hold until the fix for that #192 issue is submitted. This is so we can see the build is passing on github action after the black formatter is applied. 

As you notice, there're 52 files got changed as the result of the formatter (understandable since this is the first time the formatter is applied). We need to be cautious and make sure that the tests are passing (which would be evident through successful build) and the existing features still working as expected (through manually testing them).

This might take some time to process, but we'll get there 😉. You're doing a great job on this issue 😉👍.

**Comment by epicadk** [comment]
@vj-codes please solve the merge conflicts then this is good to go.

**Comment by vj-codes** [comment]
@epicadk should I also change the push and branch past to mention develop like last one?

**Comment by epicadk** [comment]
> @epicadk should I also change the push and branch past to mention develop like last one?

Yes please. Also the build tests are failing.

**Comment by epicadk** [comment]
You've only added the workflow right? So can you reset the branch to the develop branch and then just run black again and add the workflow? I think it would be easier than solving the merge conflicts.

**Comment by vj-codes** [comment]
@epicadk yes I'm looking into it

**Comment by vj-codes** [comment]
I was getting confused with so many file changes, so opened another PR #255 for the same,will be closing this
#255 is ready for reviewing :)

**Pull request closed without merging**
