### PR TITLE
Heroku web client typo fix

### LINKED ISSUE #179: The description for Web Client on heroku does not match
## Description
As a developer,I need to keep the heroku description updated 
so that all users are clear about the project.

1)Go to https://bridgeintech-bit-heroku-psql.herokuapp.com/
2)Read second last line about the web client 
3)It should be Bridge In Tech and not Mentorship System

## Mocks
image

### Update [Required]
- [ ] Project name is updated accordingly 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

### PR DESCRIPTION
**Pull request by Rahulm2310**
### Description
Fixes #179 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Before Changes: 
heroky-bit-typo

After Changes : 
heroku-bit-typo-fix

### Checklist:

- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@mtreacy002 @vj-codes Can you guys please review it?

**Review by chinmaym07 — COMMENTED** [review]
LGTM .Great!! 👍🏻

**Review by Aaishpra — APPROVED** [review]

**Review by vj-codes — APPROVED** [review]
LGTM 🎉

**Comment by Rahulm2310** [comment]
@vj-codes  Should I create a test report ?

**Comment by vj-codes** [comment]
@Rahulm2310 the testing has to be done by someone who is not the author of the PR .

**Review by chinmaym07 — APPROVED** [review]
The changes made in this PR were tested locally. Following are the results:
1. Code review - Done

2. All possible responses were tested as 

   - Test PR 182 -> Resolves the typo issue i.e., it has `Mentoship Backend` written on the bridge in tech Swagger UI
   - Screenshot/gif/url:
  
Screenshot_2021-02-06 Bridge In Tech API
 - Expected Result: As it is Bridge In Tech backend . Bridge In Tech should be written there .
 - Actual Result:' Mentorship Backend' is replaced by 'Bridge In Tech'

3. OS Version: Ubuntu 20.04

**Review by mtreacy002 — APPROVED** [review]
Thanks @chinmaym07 and @vj-codes for helping with the review and thanks @Rahulm2310 for your contribution 👍. Approving this now 😉

**Pull request merged**
