### PR TITLE
Updated organization name in docusaurus config

### LINKED ISSUE #291: Update organization name from AnitaB.org to anitab-org in docusaurus config
### Is your feature request related to a problem? Please describe.
Currently, the org name in docusaurus is Anitab.org but the GitHub name of the org is anitab-org
Changing the name will successfully deploy docusaurus to the gh pages

### Describe the solution you'd like
Change name as suggested above

### Describe alternatives you've considered
No alternative

### PR DESCRIPTION
**Pull request by vj-codes**
### Description

Changed organization name from AnitaB.org to anitab-org to successfully deploy docusaurus to gh pages

Fixes #291 

### Type of Change:

- Documentation

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
@vj-codes , the name change makes sense, but the docusaurus still did't get deployed to gh-pages. We just need to wait for @isabelcosta to fix the ssh-key on her side, right?

**Comment by vj-codes** [comment]
@mtreacy002 no Isabel fixed the secrets yesterday in the mentorship session and after that the workflow was running for some time and then the org error came. 
So this will be the last fix to deploy (hopefully)
[You can check the workflow here](https://github.com/anitab-org/bridge-in-tech-backend/runs/2865096740?check_suite_focus=true)

**Review by isabelcosta — APPROVED** [review]

**Review by mtreacy002 — APPROVED** [review]
LGTM 🎉🎉🎉. Thank you for your contribution, @vj-codes 🥰

**Comment by mtreacy002** [comment]
@isabelcosta and @vj-codes . The tests still [failed](https://github.com/anitab-org/bridge-in-tech-backend/pull/292/checks?check_run_id=2873577148) when I tried to re-run the workflow 😭.

**Comment by vj-codes** [comment]
`ERROR: Permission to anitab-org/bridge-in-tech-backend.git denied to deploy key ` 
@mtreacy002  Is it because Isabel created the key but you are the code owner of BIT so the key she created doesn't have access?
Just a wild guess 👀

**Comment by mtreacy002** [comment]
> `ERROR: Permission to anitab-org/bridge-in-tech-backend.git denied to deploy key ` 
> 
> @mtreacy002  Is it because Isabel created the key but you are the code owner of BIT so the key she created doesn't have access?
> 
> Just a wild guess 👀 
> 
> 

Hmmm..🤔. That makes sense. Too bad I can't create the ssh-key, since I only have limited access to the account (read and write only), even though I'm the code owner. @isabelcosta , any suggestions on how to get around this?

**Comment by mtreacy002** [comment]
Yep, based on [this](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization), only an Admin can create the ssh-key 😅

**Pull request merged**
