### PR TITLE
Feat: Issue#62 update user api endpoint

### LINKED ISSUE #73: Dev: Update user's Personal Details
## Description
As a student,
I need to create PUT /user/personal_details endpoint and tests,
so that I can give user the ability to update their Personal Details.

## Mocks
as per MVP mockup

Screen Shot 2020-07-09 at 11 04 25 am

### Update [Required]
- [ ] User can update their Personal details profile
- [ ] have these test cases: 
    * 200 - Success
    * 40x - can be Bad Request, Not Found or Unauthorized
    * 500 - Internal Server Error

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Additional Note**
This issue is part of issue #62 create/update user profile

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
Create PUT /user/personal_details api endpoint and test cases

Fixes #73 as sub-issue of #62 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
- run the app manually with [ms-bitschema-backend-server](https://github.com/mtreacy002/mentorship-backend/tree/ms-bitschema-backend-server) as MS server and this PR branch as BIT backend server. 
- As this is the first time you connect to `ms-bitschema-backend-server`, you must create a new user first, login then you can update the user profile. 

User profile before update (called using GET/user/personal_details):
Screen Shot 2020-07-09 at 9 04 40 pm

NOTE: with the current bug reported on issue [#596](https://github.com/anitab-org/mentorship-backend/issues/596) MS backend, I don't have any other option but to update ONLY the username.

Successful update message (on PUT/user/personal_details):
Screen Shot 2020-07-09 at 9 05 11 pm

Check to make sure user profile gets updated (by calling GET/user/personal_details):
Screen Shot 2020-07-09 at 9 05 31 pm

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
Note @anitab-org/bridgeintech-maintainers . 
There is a bug currently causing the internal server error. This is caused by MS schema User model has `organization` as one of the field with string data type. 

Screen Shot 2020-07-09 at 4 11 54 pm

The probleem is BIT schema uses Organization table link to MS User table as FK. So MS User model should not have `organization` stated as one of the field. This confused SQLAlchemy and raise the following error:

Screen Shot 2020-07-09 at 4 04 09 pm

I'll try to rename `organization` field on User model to something else (like `current organization` and see if that change the outcome.

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers .
I've fixed the bug by doing the followings:
* removed migration script (at the moment it's `not quite right` so will revisit later in the future as part of nice to have/future feature
* renamed `organization` field on user model to `current_organization` (incl any place where it's being used)
* refactored MS backend code to accommodate the field name changed.

This PR is now complete and ready to be reviewed.

🔊  Note for reviewer:

If you'd like to test this Update user personal details manually, you need to run MS server from `ms-bitschema-backend-server` branch from my fork repo. This branch already linked to the same database as BIT server (MS+API REST APIs and one database structure as the main target of the project)

**Comment by mtreacy002** [comment]
> Update @anitab-org/bridgeintech-maintainers .
> I've fixed the bug by doing the followings:
> 
> * removed migration script (at the moment it's `not quite right` so will revisit later in the future as part of nice to have/future feature
> * renamed `organization` field on user model to `current_organization` (incl all other places where it's being used)
> * refactored MS backend code to accommodate the field name changed.
> 
> This PR is now complete and ready to be reviewed.
> 
> 🔊 Note for reviewer:
> 
> If you'd like to test this Update user personal details manually, you need to run MS server from `ms-bitschema-backend-server` branch from my fork repo. This branch already linked to the same database as BIT server (MS+API REST APIs and one database structure as the main target of the project)

@isabelcosta and @anitab-org/bridgeintech-maintainers . The renaming User table `organization` field atm only done on my copy of MS backend. However, to make it sync, the actual MS repo will also need to be adjusted. I'm aware it's not ideal to change anything in the current MS tables especially since it's so close to production already. 
The other option (rather than changing column field on MS User table), is to change back BIT `Organization` table name to `Company`. Otherwise, I cannot think of another way to solve this.

**Review by ramitsawhney27 — APPROVED** [review]

**Review by foongminwong — APPROVED** [review]

**Comment by foongminwong** [comment]
The gif was too large to upload, this PR was tested successfully.

https://giphy.com/gifs/U1mItXgfG1MEKsuYsk (a little blurry)

**Pull request merged**
