### PR TITLE
Add missing images to ENV_SETUP_INSTRUCTION.md on Search_path section6

### LINKED ISSUE #70: Doc: Add missing images to ENV_SETUP_INSTRUCTION.md on Search_path section 6.
## Description
As a contributor,
I need to be able to see visual examples on how to setup my environment, in particular to set search_path to second bitschema,
so that I can setup BridgeInTech backend development successfully.

## Mocks
The image below shows the missing images on BIT Development Environment Setup Instructions wili that this issue is targeting.

Screen Shot 2020-06-28 at 3 57 53 pm

### Update [Required]
- [ ] provide the images described in the `TO DO` on the wiki page mentioned above. The changes is to be placed inside the ENV_SETUP_INSTRUCTION.md inside the .github folder. 
Lines to place the related TO DO:
    * below line 69
    * below line 72
    * below line 74

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by aastha985**
### Description

* Added missing images and 2 minor updates to ENV_SETUP_INSTRUCTION.md

Fixes #70 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### How Has This Been Tested?
Tested locally

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@aastha985 , your changes looks good. Although, while you're here (on section 6), can you please fix the numbering sequence (it's not your fault, the error was already there and I only just noticed it now 😊).
Screen Shot 2020-09-18 at 5 10 35 pm

**Comment by aastha985** [comment]
Sure😊, I have fixed it @mtreacy002

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@aastha985 . I've just merged few PRs including PR #139 that added image to section 3 on the same file you're working on. Can you please include these new changes from upstream develop to your code and push again?

**Comment by aastha985** [comment]
@mtreacy002 Sure, updated

**Review by mtreacy002 — APPROVED** [review]
Great job, @aastha985 . Not only you've done the required task, but also resolved the conflict well on your first PR! Thank you for contributing to the project. 🎉🎉🎉

**Comment by aastha985** [comment]
Thank you😊@mtreacy002

**Pull request merged**
