### PR TITLE
Doc: update ENV_SETUP_INSTRUCTIONS for windows/ubuntu users

### LINKED ISSUE #155: Doc: Update ENV_SETUP_INSTRUCTIONS.md with info specific to Windows/Ubuntu users
## Description
As a maintainer,
I need add setup information specific to Windows/Ubuntu users,
so that I can make sure the setup instructions are clear for users regardless of their OS machines.

## Mocks
NA

### Update [Required]
- [ ] add information specific to Windows/Ubuntu users on the ENV_SETUP_INSTRUCTIONS.md

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hour

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
Add setup information specific to Windows/Ubuntu users in particular on running tests and using db credentials

Fixes #155 

### Type of Change:
- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update

### How Has This Been Tested?
Preview the markdown doc on the fork repo pr branch

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by keshakaneria** [comment]
Do we need to write the commands too? Like for cloning the repo.

**Review by keshakaneria — APPROVED** [review]
Awesome, looks good right now :)

**Comment by mtreacy002** [comment]
>Do we need to write the commands too? Like for cloning the repo.

@keshakaneria , for cloning the repo, the contributor can click the link on the !st section and it will lead them to the detail instruction on how to do it 😉

Screen Shot 2020-09-27 at 9 30 20 pm

**Comment by keshakaneria** [comment]
> > Do we need to write the commands too? Like for cloning the repo.
> 
> @keshakaneria , for cloning the repo, the contributor can click the link on the !st section and it will lead them to the detail instruction on how to do it 😉
> 
> Screen Shot 2020-09-27 at 9 30 20 pm

Yup, thanks. I saw and thus approved the request! Amazingly documented! Thanks for this contribution 🥳

**Comment by mtreacy002** [comment]
> Awesome, looks good right now :)

Thank you @keshakaneria . Are you using Windows/Ubuntu machine? Do I need to add anything else on the instruction that is specific to Windows/Ubuntu machine that you might have experienced?

**Comment by keshakaneria** [comment]
> > Awesome, looks good right now :)
> 
> Thank you @keshakaneria . Are you using Windows/Ubuntu machine? Do I need to add anything else on the instruction that is specific to Windows/Ubuntu machine that you might have experienced?

Yes i am still using Windows machine. Even I followed the same steps and you have perfectly included every thing which we did. So if I am not wrong, nothing's missing :)

**Comment by mtreacy002** [comment]
Thank you @keshakaneria for your reassurance. 🥰😉🎉

**Review by rpattath — APPROVED** [review]

**Comment by mtreacy002** [comment]
@isabelcosta or @annabauza or @mayburgos or @anitab-org/bridgeintech-maintainers, I already have 2 approvals on this PR, can one of you please help me merge this PR? I can't do this myself since this PR was written by me. Thanks 😉

**Review by isabelcosta — APPROVED** [review]
👏 👏 👏 👏

**Pull request merged**
