### PR TITLE
docs : Add zulip badge to README

### LINKED ISSUE #149: Doc: Add project Zulip badge to README
## Description
As a contributor,
I need add the project Zulip channel to README,
so that I can clearly see where to go if I want to join the community Zulip Channel.

### Update [Required]
- [ ] Add Zulip badge to README with link to [#bridge-in-tech](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech) zulip channel 

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by Sanika1999**
### Description

Added a Zulip stream badge.

Fixes #149 

### Type of Change:

- Documentation

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Sanika1999** [comment]
Hey @mtreacy002  can you review this pr? Let me know if there are any improvements

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@Sanika1999 . Can you please move the badge to before the Bidge-In-Tech heading? Also, there's a new badge just got merged to the develop branch. Please also apply this change to your PR by pulling from the upstream develop branch.

**Comment by Sanika1999** [comment]
> @Sanika1999 . Can you please move the badge to before the Bidge-In-Tech heading? Also, there's a new badge just got merged to the develop branch. Please also apply this change to your PR by pulling from the upstream develop branch.

Sure will do that.

**Comment by Sanika1999** [comment]
@mtreacy002 Please review the changes.

**Review by gaurivn — APPROVED** [review]
bitzulipbadge
Good :tada:

**Review by mtreacy002 — APPROVED** [review]
LGTM, @Sanika1999 🎉🎉

**Review by isabelcosta — APPROVED** [review]
Great work @Sanika1999 👏

**Pull request merged**
