### PR TITLE
Setup the env BIT and MS backend server

### LINKED ISSUE #244: Task: Set up local environment
## Description
As a contributor
I need to set up local environment for bridge-in-tech-backend and send screenshots,
so that I can provide proof of the same.

## Mocks
NA

### Update [Required]
- [ ] Set up local environment (this means both BIT and MS version for BIT backends must run successfully)
- [ ] Provide a screenshot of a successful response when a user login on Swagger UI (if you haven't done this, you have to register a user first). The screenshot should look similar to the one below:
Screen Shot 2021-03-30 at 8 50 49 am

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Additional note**

**1. This is a compulsory task that must be completed before contributors can claim other Open Source Hack issues.
2. The PR that is sibmitted for this task will counted towards the `Documentation/Training` category of Open Source Hack.**. To do this you can create a new branch called `setup` and add an end of line comment inside the run.py (e.g. //Compulsory task - Setup environment) so git pick up a change in the code base. Then once you submit the PR, inside that PR description you can add the screenshot under the "How this has been tested").

### PR DESCRIPTION
**Pull request by y-martinez**
### Description

This is the proof of setup the env of project

Partial Fixes: #244 

### Type of Change:

- Documentation/Training

### How Has This Been Tested?

****This is the result successfully of the register**** 

image

****This is the result successfully of the login**** 

image

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [X] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by epicadk** [comment]
Have you setup mentorship system from @mtreacy002's fork?

**Comment by y-martinez** [comment]
> Have you setup mentorship system from @mtreacy002's fork?

The two projects must be running at the same time?

**Comment by mtreacy002** [comment]
@y-martinez , you must use `local` instead of `dev` as the value inside your `Flask_Environment_Config`
Screen Shot 2021-04-10 at 10 44 51 am

**Comment by y-martinez** [comment]
> @y-martinez , you must use `local` instead of `dev` as the value inside your `Flask_Environment_Config`
> Screen Shot 2021-04-10 at 10 44 51 am

But I don't get it, the .env configuration of the mentorship project must the same to this project?

**Comment by epicadk** [comment]
> > @y-martinez , you must use `local` instead of `dev` as the value inside your `Flask_Environment_Config`
> > Screen Shot 2021-04-10 at 10 44 51 am
> 
> But I don't get it, the .env configuration of the mentorship project must the same to this project?

Hi can you join the BIT open session today? Maybe we can help you out.

**Comment by y-martinez** [comment]
> > > @y-martinez , you must use `local` instead of `dev` as the value inside your `Flask_Environment_Config`
> > > Screen Shot 2021-04-10 at 10 44 51 am
> > 
> > 
> > But I don't get it, the .env configuration of the mentorship project must the same to this project?
> 
> Hi can you join the BIT open session today? Maybe we can help you out.

Yes sure but, what timezone is the BIT session?

**Comment by epicadk** [comment]
> > > > @y-martinez , you must use `local` instead of `dev` as the value inside your `Flask_Environment_Config`
> > > > Screen Shot 2021-04-10 at 10 44 51 am
> > > 
> > > 
> > > But I don't get it, the .env configuration of the mentorship project must the same to this project?
> > 
> > 
> > Hi can you join the BIT open session today? Maybe we can help you out.
> 
> Yes sure but, what timezone is the BIT session?

It's at 10:00 am today GMT.

**Comment by y-martinez** [comment]
> > > > > @y-martinez , you must use `local` instead of `dev` as the value inside your `Flask_Environment_Config`
> > > > > Screen Shot 2021-04-10 at 10 44 51 am
> > > > 
> > > > 
> > > > But I don't get it, the .env configuration of the mentorship project must the same to this project?
> > > 
> > > 
> > > Hi can you join the BIT open session today? Maybe we can help you out.
> > 
> > 
> > Yes sure but, what timezone is the BIT session?
> 
> It's at 10:00 am today GMT.

In 5 hours? well I will need to get up very early :sweat_smile: but ok I will try it, right now I have this error in the mentorship system from @mtreacy002's fork

image

**Comment by epicadk** [comment]
You need to use this branch https://github.com/mtreacy002/mentorship-backend/tree/ms-backend-server

**Comment by y-martinez** [comment]
Forget it, I think that I did it, I had to change in branch [https://github.com/mtreacy002/mentorship-backend/tree/ms-backend-server](https://github.com/mtreacy002/mentorship-backend/tree/ms-backend-server) of the mentorship project,

image

in the repo instructions, it did not describe this.

This is the result of the registering endpoint using the two projects

This was the result using the BIT project
image

and this was the result using the MS backend server with the  @mtreacy002 branch

image

so, I did it :sweat_smile: ?

**Comment by epicadk** [comment]
Yes. Good job. 👍🏼

**Comment by y-martinez** [comment]
> Yes. Good job. 👍🏼

Nice! :sunglasses: well I updated the PR with the proof of setup :+1:

**Comment by epicadk** [comment]
Good job. Closing because this won't be merged. Will be accepted for OSH. 👍🏽

**Comment by mtreacy002** [comment]
> in the repo instructions, it did not describe this.

@y-martinez , probably you missed this. It is actually mentioned in the setup instruction for BIT backend under step 9 as can be seen below.
image

**Comment by mtreacy002** [comment]
> so, I did it 😅 ?

Well done @y-martinez 🎉🎉. Don't forget that you need to make sure you've successfully login as per mentioned in the issue #244. 

image

So you're halfway there 👍. Just confirm your email and login from swagger UI 😉. Cc @epicadk

**Comment by epicadk** [comment]
> > so, I did it 😅 ?
> 
> Well done @y-martinez 🎉🎉. Don't forget that you need to make sure you've successfully login as per mentioned in the issue #244.
> 
> image
> 
> So you're halfway there 👍. Just confirm your email and login from swagger UI 😉. Cc @epicadk

Oops yes please do this.

**Comment by y-martinez** [comment]
> > so, I did it sweat_smile ?
> 
> Well done @y-martinez . Don't forget that you need to make sure you've successfully login as per mentioned in the issue #244.
> 
> image
> 
> So you're halfway there . Just confirm your email and login from swagger UI . Cc @epicadk

Yes I updated the PR with the proof of login successful

**Comment by mtreacy002** [comment]
> Forget it, I think that I did it, I had to change in branch [https://github.com/mtreacy002/mentorship-backend/tree/ms-backend-server](https://github.com/mtreacy002/mentorship-backend/tree/ms-backend-server) of the mentorship project,

image

> in the repo instructions, it did not describe this.

Or perhaps you're referring to step 8?
image

**Comment by y-martinez** [comment]
The screenshot in the issue

> > Forget it, I think that I did it, I had to change in branch https://github.com/mtreacy002/mentorship-backend/tree/ms-backend-server of the mentorship project,
> 
> image
> 
> > in the repo instructions, it did not describe this.
> 
> Or perhaps you're referring to step 8?
> image

No, I mean the instructions for the configuration of the [mentorship-backend](https://github.com/anitab-org/mentorship-backend) project, it is not specified that it was necessary to uncomment those lines. 

Do I write a comment with the screenshot of the login successful in the issue #244 ?

**Comment by mtreacy002** [comment]
> Do I write a comment with the screenshot of the login successful in the issue #244 ?

@y-martinez , you don't need to, since as long as you refer the issue in this PR description, it'll show up on that issue so mentors can check the pr out to see if it is done or not.

Screen Shot 2021-04-11 at 7 08 35 pm

**Pull request closed without merging**
