### PR TITLE
Dev  refactor date fields to a human readable format

### LINKED ISSUE #115: Dev: Refactor date fields on endpoints to use a human readable format
## Description
As a GSoC student,
I need refactor all the date fields on API endpoints to use RFC 2822,
so that I can shift the logic for date conversion to be at the backend instead of frontend.

## Mocks
NA

### Update [Required]
- [ ] Refactor all existing date fields to use RFC 2822 (e.g. Thursday, 31-Dec-20 00:00:00 UTC)

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
Refactor date fields in BIT API endpoints to accept and view human readable date.
The input fields take the format of YYYY-MM-DD HH:MM where user put the date and time relevant to their local time. The system converts any input to UTC datetime so the database keep all datetime related data in UTC time.
Any user retrieving the data regardless whether the data was created/updated by them will be shown the date and time in their own local time. The return date has the format of YYYY-MM-DD HH:MM Z where Z is the logged in user timezone info.

**IMPORTANT** to test this PR, you must drop the existing database tables and all enum types under the Types directory under bitschema schema. 

This is because:
* the data you have is no longer valid for timezone enum related fields
* I have change the list of enum to reflect the pytz library `all_timezones` list (~600 timezones) to cover as wide range of timezone possible  

Fixes #115 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
- create the followings:
  * create a user, verify email, login (for this user, I creeated user mtreacy01 and used `Europe/London` as timezone
  * create user additional info with `is_organization_rep` value is True 
- create an organization
    * send GET/organizations to view all organizations in the record. You'll see the organization that you've just created. On successful reesponse, see below. (Notice that the date is a human readable date and it has the logged-in user's timezone info attached to it to avoid ambiguity)
Screen Shot 2020-08-21 at 10 22 22 am

- create a program with start and end date using format as mentioned in the `model` of the input fields
  * send GET /organizations/{organization_id}/programs request. On successful process see below.  
Screen Shot 2020-08-21 at 10 23 05 am
Screen Shot 2020-08-21 at 10 23 21 am

To check that other user see the dates in their own timezone interpretation, do the followings:
- create another user (for this I created user ksmith01 and used `Australia/Melbourne` as timezone
- login and send GET /organizations request. On successful process see below. Notice that the creation_date was shown in ksmith timezone:
Screen Shot 2020-08-21 at 10 24 20 am

- send GET/organizations/{organization_id}/programs. On successful process see below (again, noticed that all dates are shown in ksmith timezone, not in mtreacy's timezone whose the owner of the organization and program data)
Screen Shot 2020-08-21 at 10 24 49 am
Screen Shot 2020-08-21 at 10 25 02 am

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers , I've refactored the date fields for API endpoints date fields. They are now showing and accepting string input with format `YYYY-MM-DD HH:MM`. 
**IMPORTANT** to test this PR, you must drop the existing database tables. This is because of 2 things:
* the data you have is no longer valid for timezone enum related fields
* I have change the list of enum to reflect the pytz library `all_timezones` list (~600 timezones) to cover as wide range of timezone possible.  

Please review when you have time. Thanks

**Review by ramitsawhney27 — DISMISSED** [review]

**Comment by mtreacy002** [comment]
Update @ramitsawhney27 and @anitab-org/bridgeintech-maintainers . I've removed the need for timezone cookie. I Also have removed the is_organization_rep as per changes in PR #114 . Please re-review. Thanks

**Comment by meenakshi-dhanani** [comment]
@mtreacy002 need to resolve conflicts

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've just resolved the conflict. Can you please re-review/re-approve? Thanks

**Review by meenakshi-dhanani — APPROVED** [review]

**Comment by mtreacy002** [comment]
@ramitsawhney27 , can you please re-approve and merged this PR? @meenakshi-dhanani has given her approval. Thanks  @meenakshi-dhanani and @ramitsawhney27 .

**Review by ramitsawhney27 — APPROVED** [review]

**Pull request merged**
