### PR TITLE
doc: Add CodeCov badge to README.md

### LINKED ISSUE #148: Doc: Add CodeCov badge to README
## Description
As a contributor,
I need to see the CodeCov badge on README,
so that I know the percentage of code being covered by the test cases.

## Mocks
NA

### Update [Required]
- [ ] Add CodeCov badge to README. Refer to [this](https://stackoverflow.com/questions/54010651/codecov-io-badge-in-github-readme-md) resource on how to do it.

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by khushishikhu**
### Description

Added codecov badge to Readme.md

Fixes #148

### Type of Change:

- Code
- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by khushishikhu** [comment]
@mtreacy002  please review this PR

**Comment by mtreacy002** [comment]
@khushishikhu, the change looks good. But can you change the title of this PR to show the actual change made to the README file? Since we'll have many updates probably done to README, so, it's good to be more specific. Like in your case,  you could change the title to `Add CodeCov badge to README.md`.

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@khushishikhu , can you please add the badge before the `Bridge-In-Tech` heading? Also there is a new travis badge has just got added to this README. Can you accommodate this change onto your PR branch by pulling the latest change from the upstream develop? Thanks

**Comment by khushishikhu** [comment]
@mtreacy002 please have a look now

**Review by mtreacy002 — DISMISSED** [review]
LGTM, @khushishikhu . 🎉🎉

**Comment by mtreacy002** [comment]
@khushishikhu , this PR looks good to me, so I have approved it. But there's a conflict with the recent merged to develop. Can you please integrate that recent update to your code (this can be done by pull --rebase from the upstream develop branch)? Thanks

**Comment by khushishikhu** [comment]
@mtreacy002 i think now this is resolved. please have a look now

**Review by mtreacy002 — APPROVED** [review]
Thank you, @khushishikhu for resolving the conflict and accommodating the recent change to your PR. 😉

**Pull request merged**
