### PR TITLE
Dev: using namedtuple decorator for HTTP response

### LINKED ISSUE #61: Development: Using named tuples/dictionary rather than tuple for responses
**Is your feature request related to a problem? Please describe.**
Technical debt is added by using unnamed tuples rather than named tuples/dictionaries for storing responses in both BIT and from MS

**Describe the solution you'd like**
Replace tuples with named tuples/dictionaries

**Describe alternatives you've considered**
Please analyze between dictionaries vs named tuples
Please consider using decorators (https://www.python.org/dev/peps/pep-0318/)

**Additional context**

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description

Employed python decorator to convert HTTP responses from tuple to namedtuple.

Fixes #61

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Running existing tests
Running the app and register a new user with successful result

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] New and existing unit tests pass locally with my changes **WIP**

### CODE REVIEW

**Comment by mtreacy002** [comment]
@anitab-org/bridgeintech-maintainers and @ramitsawhney27. I've created the decorator to convert tuple to namedtuple for HTTP responses.
Most of the tests passed except for the one with mismatch cross project issues between MS and BIT (immediate ones are [#647](https://github.com/anitab-org/mentorship-backend/pull/647) and [#650](https://github.com/anitab-org/mentorship-backend/pull/650#issuecomment-649476015).

The problem arises from trying to mask the namedtuple attribute status_code from whatever code being returned by MS to the code expected by BIT standard. 
On my base code, I placed the following to mask the responses:
Screen Shot 2020-06-25 at 8 52 19 pm

error on swagger ui for username already exist
Screen Shot 2020-06-25 at 9 43 05 pm


The problem comes in the setting of the namedtuple which is not as straight forward. Without masking (returning as is from MS) we don't need line 46-51 and 54-69 in the screenshot above. It'll be just a simple line.

If we still want to mask it now (only to remove it back once MS issues is fixed), I still need to workout to replace value of namedtuple status_code attribute according to 
Screen Shot 2020-06-25 at 8 51 32 pm
 
(meaning I still need to fix line 54-69 which causes the error for test cases).
My question is, do I really need to do these extra lines (which is not just 2 or 3 lines) so we can get the HTTP error code as what BIT wants, only to delete it again once MS issues are fixes?
Or is it ok to just show the response as it is for now, and just  convert tuple to namedtuple?
Please advise. Thanks

**Comment by mtreacy002** [comment]
there is also [this discussion](https://stackoverflow.com/questions/19257497/cant-set-attribute-for-subclasses-of-namedtuple) on stackoverflow about namedtuple as immutable therefor shouldn't be manipulated. Instead if we need to change the value, we need to use [recordtype](https://pypi.org/project/recordtype/) instead of namedtuple. But, I feel it's pointless since this is just a temporary measure until the error codes in MS are all fixed. Should we go to that length if we are to mask our responses?

**Comment by mtreacy002** [comment]
Fix tests on expected code (since it's mocking API I can pretend return value is correct) 😁. But still have to troubleshoot replacing values of namedtuple for masking http responses

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers 
I've managed to set attribute for masking responses on HTTP error code on the namedtuple.

Screen Shot 2020-06-26 at 12 35 34 am

@ramitsawhney27 , I've changed the Register test quite significantly to accommodate the namedtuple. For the simplicity purposes, can I let PR #59  and PR #60  as it is (not changing it) since once this PR is approved on top of them, the code changes here will automatically apply. Or do you want me to go back to change PR #59 and #60 accordingly?

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers. I've pull rebased the changes done to PR #59 and #60 per mentors' feedback onto this PR as well, so they're now in sync.

**Review by ramitsawhney27 — DISMISSED** [review]
Much better, looks much more readable, and cleaner. I agree with all your comments above. Great work!

**Review by ramitsawhney27 — DISMISSED** [review]

**Review by foongminwong — DISMISSED** [review]

**Comment by foongminwong** [comment]
@mtreacy002 can you fix the two conflicting files (`ms_api_utils.py`, `users.py`) before we merge them?

**Comment by mtreacy002** [comment]
Yep, @foongminwong , I've just fixed the merge conflict. Can you please continue with the review and merging? Thanks heaps...😉

**Review by ramitsawhney27 — APPROVED** [review]

**Review by foongminwong — APPROVED** [review]

**Pull request merged**
