### PR TITLE
Issue#84 test cases for get personal background api

### LINKED ISSUE #84: Dev: Test cases for POST and GET /user/personal_background
## Description
As a student,
I need write test cases for POST and GET /user/personal_background api endpoints,
so that I can ensure the code quality of the project.

## Mocks
NA

### Update [Required]
- [ ] for successful POST /user/personal_background with response 201 - Created
- [ ] for successful GET /user/personal_background with response 200 - Ok
- [ ] for each POST and GET, write tests for any of the 40x responses (such as 400 - Bad request, 404 - Not Found, 409 - Conflict, etc) and/or 500 Internal server error

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Additional note**
This issue is a part of issue #62 (Create/update user profile) and issue #63 (Get user profile)

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
Test cases for POST and GET /user/personal_background api endpoints.

Fixes #84 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
By running tests on VSCode Tests Explorer and python unittest with result all tests passed.
Screen Shot 2020-07-16 at 10 07 35 pm

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . Here's the test cases for the POST and GET /user/perrsonal_background api endpoints (PR #82 ). Please review when you have time. Ta

**Review by ramitsawhney27 — DISMISSED** [review]

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've made the changes to Background enum logic as discussed on our BIT weekly meeting. Please re-review when you have time. Thanks

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've just force pushed changes to add other fields for physical and mental ability as well as socio-economic status

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've resolved merge conflict and pull rebase changes from PR #80 and #82 on bugs fixes. Please check this out when you have time, thanks

**Review by ramitsawhney27 — DISMISSED** [review]
The revisions look fine to me

**Comment by foongminwong** [comment]
@mtreacy002 review the following conflicting files when you have time 👍

**Comment by mtreacy002** [comment]
> @mtreacy002 review the following conflicting files when you have time 👍

Will do that now, @foongminwong  😉

**Comment by mtreacy002** [comment]
@foongminwong and @ramitsawhney27 I've just resolved the merge conflict and force pushed the changes. Can you please approve and merge this PR? Thanks

**Review by foongminwong — DISMISSED** [review]
👍

test-pr-85

**Review by ramitsawhney27 — DISMISSED** [review]

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers. From this PR to thee next in queue,  I need to refactor POST/PUT so, please DO NOT MERGE this one till I complete refactoring. Ta

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've removed POST /user/personal_background and test create personal background from this PR as the POST is no longer used as API as per our discussion. Please note that this PR is blocked by PR #101

**Review by ramitsawhney27 — DISMISSED** [review]

**Comment by mtreacy002** [comment]
Update @ramitsawhney27 and  @anitab-org/bridgeintech-maintainers . I've resolved the merge conflict on this PR. can you please continue with the merging? Thanks

**Review by foongminwong — APPROVED** [review]

**Comment by mtreacy002** [comment]
@ramitsawhney27 , can you please re-approve this PR so it can be merged? Thanks

**Review by ramitsawhney27 — APPROVED** [review]

**Pull request merged**
