### PR TITLE
[Chore] Update GitHub actions

### LINKED ISSUE #262: Fix tests failing on github actions
### Describe the bug

Tests on github actions are failing.

### To Reproduce
1. Check the actions tab 

### Expected behavior

Tests should not fail

### PR DESCRIPTION
**Pull request by y-martinez**
### Description

This PR adds:

- Update the `main.yml` with the health check of the postgresql container, avoiding problems with running tests in the workflow

Fixes #262 

### Type of Change:

- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [X] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [X] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings

- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by epicadk** [comment]
@y-martinez I think this is good enough. Did you have some other changes in mind? If not please mark it as ready for review.

**Comment by y-martinez** [comment]
> @y-martinez I think this is good enough. Did you have some other changes in mind? If not please mark it as ready for review.

Yes, I am testing, but yes I marked it as ready for review :)

**Review by epicadk — APPROVED** [review]
👍🏼 looks good. @mtreacy002 please review this and merge asap. It is essential for github actions to run properly.

**Review by mtreacy002 — APPROVED** [review]
@y-martinez , well done for the fix. Thank you so much for contributing to the project 🎉🎉🎉.

**Pull request merged**
