### PR TITLE
Issue#86 PUT /user/personal_background api endpoint and tests

### LINKED ISSUE #86: Dev: PUT /user/personal_background api endpoint and test cases
## Description
As a student,
I need to create PUT /user/personal_background api endpoint,
so that I can give user the ability to update their Personal Background information.

## Mocks
NA

### Update [Required]
- [ ] User can update their Personal Background information
- [ ] include relevant test cases

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Additional note**
This issue is a part of issue #62 (Create/update user profile)

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
Allow user to update their personal background data

Fixes #86 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
- Login as a user that has no perrsonal background data and get personal details (GET /user/personal_details) so the user_id is saved to cookie.
- send PUT /user/personal_background request and on successful create, see response 201 Created as per screenshot below
Screen Shot 2020-08-03 at 9 57 43 pm

- now test update by modifying the personal background. On successful update see response 200 OK as per screenshot below 
Screen Shot 2020-08-03 at 9 58 06 pm

* with invalid new personal background data payload
Screen Shot 2020-08-03 at 10 19 20 pm

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . Here's the PR for PUT /user/personal_background api endpoint and tests. please provide feedback whenever you're available. Thanks

**Review by ramitsawhney27 — DISMISSED** [review]
Looks good. I like the very detailed docstrings, makes the review and understanding much easier for me!

**Comment by mtreacy002** [comment]
> Looks good. I like the very detailed docstrings, makes the review and understanding much easier for me!

thank you @ramitsawhney27 for your kind feedback.

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've modified the background enum logic on backend as discussed in the last BIT weekly meeting. Please re-review once you have time. Thanks

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've just force pushed changes to add other fields for physical and mental ability as well as socio-economic status

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I'vee resolved the mergee conflicts and applied bug fixes discussed on [zulip post](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/Bugs.20.26.20Fixes/near/205030500) and issue #94 (temporary solution for local environment only).

**Review by ramitsawhney27 — DISMISSED** [review]

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've refactor this PR to use only one API endpoint PUT /user/personal_background for both create and update user personal background information. Please review when you have time.

**Review by foongminwong — COMMENTED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses were tested as below:

   * _Test PR 87 (Create non-existing personal background)_  
      _Screenshot/gif/url_:  

     
     test-bit-backend-pr-87-create


      _Expected Result_:  As a user, I should be able to create personal background using `PUT /user/personal_background`
      _Actual Result_:

   * _Test PR 87 (Update existing personal background)_  
    _Screenshot/gif/url_:  

     
     test-bit-backend-pr-87-update


      _Expected Result_:  As a user, I should be able to update existing personal background using `PUT /user/personal_background`
      _Actual Result_: Same as expected

3. OS Version: Windows 10

4. Tested JSON:

```json

{
  "gender": "Prefer not to say",
  "age": "Prefer not to say",
  "ethnicity": "Prefer not to say",
  "sexual_orientation": "Prefer not to say",
  "religion": "Prefer not to say",
  "physical_ability": "Prefer not to say",
  "mental_ability": "Prefer not to say",
  "socio_economic": "Prefer not to say",
  "highest_education": "Prefer not to say",
  "years_of_experience": "Prefer not to say",
  "gender_other": "Prefer not to say",
  "ethnicity_other": "Prefer not to say",
  "sexual_orientation_other": "Prefer not to say",
  "religion_other": "Prefer not to say",
  "physical_ability_other": "Prefer not to say",
  "mental_ability_other": "Prefer not to say",
  "socio_economic_other": "Prefer not to say",
  "highest_education_other": "Prefer not to say",
  "is_public": true
}

```

**Review by foongminwong — DISMISSED** [review]

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've just resolved the merge conflict on this PR. Please re-approve and only merge this PR after the PR #85 which is this PR's blocker is merged to develop. Thanks

**Review by foongminwong — APPROVED** [review]

**Review by ramitsawhney27 — APPROVED** [review]

**Review by ramitsawhney27 — APPROVED** [review]

**Pull request merged**
