### PR TITLE
Doc: Created GETTING_STARTED.md file inside .github folder

### LINKED ISSUE #142: Doc: Create GETTING_STARTED.md file inside .github folder
**Is your feature request related to a problem? Please describe.**
The [Getting Started](https://github.com/anitab-org/bridge-in-tech-backend/wiki/Getting-Started) page on the bridge-in-tech-backend wiki is currently not written as a markdown document, but directly written as a wiki page. The content on this page needs to be made available to contributors so they can also involve in improving the page documentation.

**Describe the solution you'd like**
Create a markdown file `GETTING_STARTED.md` inside `.github` folder and place the content on the  [Getting Started](https://github.com/anitab-org/bridge-in-tech-backend/wiki/Getting-Started) page inside that doc so that the wiki sidebar can refer to the doc instead of having the content written as a wiki page.

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by anishghimire603**
### Description

Created a markdown file <code> GETTING_STARTED.md </code> inside <code> .github </code> folder and placed the content on the Getting Started page inside that doc so that the wiki sidebar can refer to the doc instead of having the content written as a wiki page.

Fixes #142

### Type of Change:

- Documentation

### How Has This Been Tested?
I tested this documentation changes in my own project repo readme.md file.
Doc: image

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by anishghimire603** [comment]
@mtreacy002 have a look please.

**Review by mtreacy002 — APPROVED** [review]
Greeat job, @anishghimire603. You've completed your first task 🎉🎉
Thanks again for your contribution. Look forward to your next PR 😉.

**Comment by anishghimire603** [comment]
> Greeat job, @anishghimire603. You've completed your first task 🎉🎉
> Thanks again for your contribution. Look forward to your next PR 😉.

Welcome @mtreacy002 love to contribute more in <a href= "https://github.com/anitab-org" > Anitab.org </a>

**Comment by mtreacy002** [comment]
Just one minor thing, @anishghimire603 . Can you please add `Doc: ...` in front of the title of this PR, this is so we now what type of PR this is. 😉

**Comment by mtreacy002** [comment]
Also, @anishghimire603, make sure on your next commit, you follow the [commit style guideline](https://github.com/anitab-org/bridge-in-tech-web/wiki/Commit-Message-Style-Guide) that is mentioned inside the doc you've just created.

**Comment by anishghimire603** [comment]
> Just one minor thing, @anishghimire603 . Can you please add `Doc: ...` in front of the title of this PR, this is so we now what type of PR this is. 😉

sure I will edit it and will follow commit style guide

**Pull request merged**
