### PR TITLE
refactor: Remove dependencies from requirements file

### LINKED ISSUE #166: Auditing the dependencies by fixing/upgrading/removing them
**Is your feature request related to a problem? Please describe.**
In the requirements file, there are a lot of dependencies that cause various bugs and conflicts similar to #157 

**Describe the solution you'd like**
We should manually audit the requirements file to keep the required packages only.

**Describe alternatives you've considered**
I would suggest to not use `pip freeze`  command for generating requirements file onwards. Also, this can be added as a check in pull request template and contribution guidelines so that contributors can keep a track of this.

### PR DESCRIPTION
**Pull request by devkapilbansal**
### Description
Removed Dependencies from Requirements and updated other packages. Now, pip will automatically solve conflicts while downloading dependencies

Fixes #166 

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Run `python -m unittest discover tests` locally to ensure all tests passed.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by devkapilbansal** [comment]
@mtreacy002 review this pull request. Also, can you please confirm once if `flask-restplus` is useful or not.

**Comment by devkapilbansal** [comment]
Although Travis CI build failed but these changes can be tested locally by changing time of the system

**Review by mtreacy002 — COMMENTED** [review]
@devkapilbansal . can you please tell me the method you are using to know which dependencies are needed which one is not? Is it by making own judgement or checking by running some pip (or other) command that checks if the dependencies being used in the application. I'm asking since I've seen a couple of dependencies that being used but got removed by this PR. For example, we usee pytz for date conversion but not sure why you remove it here.
Screen Shot 2020-10-04 at 10 54 22 am

Also, many of the dependencies under the requirements.txt are subdependencies that comes with a depencency. I understand that we don't need to have them in the requirements.txt since the main dependency will automatically installed it. But can you tell me what method you use to know which ones are the nested dependencies  and which ones are the parent dependencies? I'm interested to know more about this.

**Comment by mtreacy002** [comment]
> @mtreacy002 review this pull request. Also, can you please confirm once if `flask-restplus` is useful or not.

On this, we're using only the flask-restx. I left the flask-restplus in the requirements.txt before since during GSoC, MS was in transition to move from flask-restplus to flask-restx. But now it's completed (MS only has flask-restx) so it's save to remove this from BIT as well. 😉

**Comment by devkapilbansal** [comment]
> @devkapilbansal . can you please tell me the method you are using to know which dependencies are needed which one is not? Is it by making own judgement or checking by running some pip (or other) command that checks if the dependencies being used in the application. I'm asking since I've seen a couple of dependencies that being used but got removed by this PR. For example, we usee pytz for date conversion but not sure why you remove it here.
> Screen Shot 2020-10-04 at 10 54 22 am
> 
> Also, many of the dependencies under the requirements.txt are subdependencies that comes with a depencency. I understand that we don't need to have them in the requirements.txt since the main dependency will automatically installed it. But can you tell me what method you use to know which ones are the nested dependencies and which ones are the parent dependencies? I'm interested to know more about this.

I removed pytz because it is a sub-dependency of APScheduler too. I manually checks for the sub dependecies of each dependencies using git blame, installing them in a new environment or a google search.

**Comment by devkapilbansal** [comment]
By installing the libraries it can be seen from terminal that pip tries to install pytz twice, once with APScheduler and other from the file itself. Therefore I removed pytz from requirements file.

**Comment by mtreacy002** [comment]
> > @devkapilbansal . can you please tell me the method you are using to know which dependencies are needed which one is not? Is it by making own judgement or checking by running some pip (or other) command that checks if the dependencies being used in the application. I'm asking since I've seen a couple of dependencies that being used but got removed by this PR. For example, we usee pytz for date conversion but not sure why you remove it here.
> > Screen Shot 2020-10-04 at 10 54 22 am
> > Also, many of the dependencies under the requirements.txt are subdependencies that comes with a depencency. I understand that we don't need to have them in the requirements.txt since the main dependency will automatically installed it. But can you tell me what method you use to know which ones are the nested dependencies and which ones are the parent dependencies? I'm interested to know more about this.
> 
> I removed pytz because it is a sub-dependency of APScheduler too. I manually checks for the sub dependecies of each dependencies using git blame, installing them in a new environment or a google search.

I see... Also, have you run the app in the new environment? did all the existing functions work as expected?

**Comment by devkapilbansal** [comment]
@mtreacy002 yes I did. Also I tested it with the new tokens for which you make the pull request. All test cases pass there too.

**Comment by mtreacy002** [comment]
> @mtreacy002 yes I did. Also I tested it with the new tokens for which you make the pull request. All test cases pass there too.

That's good. Ok, I think this is good then. But I will approve this as soon as I change the timestamp as requested by Isabel on PR #167 . Thank you so much for your detail explanation 😉

**Comment by devkapilbansal** [comment]
@mtreacy002 I rebased it to current develop branch. Please review it now

**Review by mtreacy002 — APPROVED** [review]
This PR is tested locally on MacOS Catalina 10.15.7. The test was done by performing the following steps:
* created a new virtual environment
* reinstalled dpendencies by running `pip install -r requirements.txt`
* run the app on most of existing features and confirmed that they run as normal

@ramitsawhney27 and @isabelcosta, can you please also help give your review here?
Thanks

**Review by isabelcosta — APPROVED** [review]
Thank you for your contribution @devkapilbansal 🎉

**Comment by isabelcosta** [comment]
@mtreacy002 feel free to merge ;)

**Comment by mtreacy002** [comment]
> @mtreacy002 feel free to merge ;)

Thank you, @isabelcosta and @devkapilbansal . Will merge the PR now 😉

**Pull request merged**
