### PR TITLE
Add Maya as a CodeOwner

### PR DESCRIPTION
**Pull request by epicadk**
Refer to zulip post [here](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/general/near/241684404).

### CODE REVIEW

**Review by mtreacy002 — COMMENTED** [review]
@epicadk . Thanks for doing this. Just curious, don't the main workflow file also needs to be modified (as per what was done on ms [pr-1103](https://github.com/anitab-org/mentorship-backend/pull/1103/files)?

**Comment by epicadk** [comment]
> @epicadk . Thanks for doing this. Just curious, don't the main workflow file also needs to be modified (as per what was done on ms [pr-1103](https://github.com/anitab-org/mentorship-backend/pull/1103/files)?

We don't have the `Paths ignore` on BIT that's why I haven't added it. This would still work. All that line does is avoid triggering workflows when the only change made is in the `CODEOWNERS` file

**Comment by mtreacy002** [comment]
> > @epicadk . Thanks for doing this. Just curious, don't the main workflow file also needs to be modified (as per what was done on ms [pr-1103](https://github.com/anitab-org/mentorship-backend/pull/1103/files)?
> 
> We don't have the `Paths ignore` on BIT that's why I haven't added it. This would still work. All that line does is avoid triggering workflows when the only change made is in the `CODEOWNERS` file

I see, thank you for explaining this, @epicadk. I'm learning something new here. I'm approving this then 😉.

**Review by mtreacy002 — APPROVED** [review]
Thanks, @epicadk for creating this. I'm approving this now. @isabelcosta, can you please confirm that this is OK?

**Review by vj-codes — APPROVED** [review]
👍

**Review by isabelcosta — APPROVED** [review]
Awesome!

**Pull request merged**
