### PR TITLE
chore: Add BIT web remote github.io to CORS origins

### LINKED ISSUE #271: Dev: Add BIT web gh-pages remote to CORS
## Description
As a contributor,
I need to add BIT web remote server on gh-pages to CORS
so that I can use the BIT web gh-pages as an alternative UI if I want to.

### Update [Required]
- [ ] add BIT web remote url `https://anitab-org.github.io` to CORS

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hr

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
Add https://anitab-org.github.io/bridge-in-tech-web/ to CORS origin so that user can use remote BIT web as frontend application with local BIT backend running.

Fixes #271 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Steps:
1. Run BIT and MS backends on local machine
2. go to https://anitab-org.github.io/bridge-in-tech-web
3. See Homepage with Main Navbar showing default (indicated by `Sign In` and `Sign Up` on the right)
4. login as existing user
5. See Homepage with the logged-in Main navbar (indicated by `Sign Out` tab on the right) and the Sidebar for members navigation.
ezgif com-gif-maker (68)

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Rahulm2310 — APPROVED** [review]
LGTM

**Review by vj-codes — APPROVED** [review]
LGTM 🎉

**Comment by mtreacy002** [comment]
Thank you @vj-codes and @Rahulm2310 . @isabelcosta , can you please help with the merging as we have got 2 approving reviews. Thank yo for your help 😉

**Comment by vj-codes** [comment]
@mtreacy002 do you mean testing because I don't think we have merge access 👀

**Review by isabelcosta — APPROVED** [review]
Awesome!
@mtreacy002 thank you for the ping!

**Comment by isabelcosta** [comment]
@mtreacy002 hope this will work 🤗 💪🏾

**Pull request merged**
