### PR TITLE
clean: Removed ".github/ISSUE_TEMPLATES" from the repository

### LINKED ISSUE #201: Remove .github/ISSUE_TEMPLATE folder
### Description
As a org admin / maintainer,
I need to maintain 1 version of issue templates used in the organization,
so that I can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on https://github.com/anitab-org/.github, we don't need to have issue templates present in the repository. Read more about these type of files here https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

### Acceptance Criteria
**Update [Required]**

- [ ]  Delete .github/ISSUE_TEMPLATE

**Definition of Done**

- [ ]  All of the required items are completed.
- [ ]  Approval by 1 mentor.

**Estimation**
0.5 hours

### PR DESCRIPTION
**Pull request by sahil9001**
### Description

Removed the ".github/ISSUE_TEMPLATE" folder from the repository.
Fixes #201 

### Type of Change:

- Quality Assurance
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sahil9001** [comment]
@mtreacy002 @vj-codes

**Review by Rahulm2310 — COMMENTED** [review]
Good Job 🎉 . @sahil9001 Thanks for your contribution.

**Review by vj-codes — DISMISSED** [review]
@sahil9001 congrats on your first contribution 🎉

**Comment by vj-codes** [comment]
@Rahulm2310 have you approved these changes ? I can't see a checkmark beside your name , please confirm so that the label can be updated accordingly

**Review by Rahulm2310 — DISMISSED** [review]

**Comment by vj-codes** [comment]
@mtreacy002 I'll add ready to merge label since this has 2 approving reviews and it's a documentation change no testing needed thus it's unlikely to break anything , is it fine ?

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@sahil9001 , can you also please change the links referred to these templates (in .github/CONTRIBUTING.md) to the relevant links from anitab-org/.github referred to by @vj-codes in this issue #201 description? Otherwise the links will get HTTPError page 404 Not Found.

**Comment by mtreacy002** [comment]
> @mtreacy002 I'll add ready to merge label since this has 2 approving reviews and it's a documentation change no testing needed thus it's unlikely to break anything , is it fine ?

@vj-codes , we must be careful when deleting these documentations from .githhub. Any place where the document is referred to inside our wiki pages will get HTTPError 404 Not Found if the link is not replaced with an active link accordingly 😉.

**Comment by sahil9001** [comment]
To be clear, I didn't dismiss any review, I just pushed my changes via github CLI. @Rahulm2310 @vj-codes @mtreacy002

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@sahil9001 , there is one more place where ISSUE_TEMPLATE Is referred to in this repo, that is in the `config.yml` (line 11). Can you please change this as well? Thanks
Screen Shot 2021-02-27 at 9 37 58 pm

**Comment by sahil9001** [comment]
> @sahil9001 , there is one more place where ISSUE_TEMPLATE Is referred to in this repo, that is in the `config.yml` (line 11). Can you please change this as well? Thanks
> Screen Shot 2021-02-27 at 9 37 58 pm

Yeah sure its done!

**Review by mtreacy002 — COMMENTED** [review]
Well done with the fix, @sahil9001. One last step. It is recommended for contributor to squash their commiits into one. Will you be able to do this? If you're not sure how, I can give you some hints if you'd like to learn. Alternatively, I can squash and merge from my end as well. Let me know which one you'd prefer doing.

**Comment by sahil9001** [comment]
@mtreacy002 From next PRs I'll squash commits, only for this PR you do it from your end!

**Review by mtreacy002 — APPROVED** [review]
Approving this PR now. Thank you again for your contribution, @sahil9001 🎉🎉🎉.

**Pull request merged**
