### PR TITLE
Feat: Issue#82 POST and GET /user/personal_background api endpoints

### LINKED ISSUE #82: Dev: POST and GET /user/personal_background api endpoints
## Description
As a student,
I need to create POST and GET /user/personal_background endpoints,
so that I can give user the ability to create and get their Personal Background information.

## Mocks
NA

### Update [Required]
- [ ] User can create their Personal Background information
- [ ] User can get their Personal Background information

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Additional notee**
This issue is a part of issue #62 (Create/update user profile) and #63 (Get user profile)

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
Give user the ability to create and get their personal background information.

Fixes #82 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
- Tested manually by sending POST /user/personal_background (to create personal background of existing user).
* on successful output - personal background information successfully created:
Screen Shot 2020-07-16 at 5 51 42 pm

* when user already has existing personal background information in the database:
Screen Shot 2020-07-16 at 5 53 42 pm

- tested manually by sending GET /user/personal_background (to get their personal background information):
* on successful output:
Screen Shot 2020-07-16 at 4 52 26 pm

* on error response - user has no personal background information in the database:
Screen Shot 2020-07-16 at 3 54 32 pm
 

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

**Additional note**
* Test cases will be done on a separate PR.
* Personal Background enum input must be taken from the Background enum **VALUE** from within `app/utils/bitschema_utils.py` file.

### CODE REVIEW

**Comment by mtreacy002** [comment]
Update @ramitsawhney27 and @anitab-org/bridgeintech-maintainers . Here's PR for POST and GET /user/personal_background api endpoints. The test cases will be submitted separately. Look forward to hear your feedback.

**Review by ramitsawhney27 — DISMISSED** [review]
This PR (+the tests) look coherent. Good work!

**Comment by mtreacy002** [comment]
> This PR (+the tests) look coherent. Good work!

Thanks, @ramitsawhney27

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've modified background enum logic as per our discussion on BIT weekly meeting. Please re-rerview. Thanks

**Review by ramitsawhney27 — DISMISSED** [review]

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've just force pushed changes to add other fields for physical and mental ability as well as socio-economic status.

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've solved merge conflict, fix bug as mentioned on [zulip post](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/Bugs.20.26.20Fixes/near/205030500), and temporarily fix bug as reported on issue #94 (similar approach also applied on PR #80).
Can you please re-review when you have time? Thanks

**Review by ramitsawhney27 — DISMISSED** [review]

**Review by foongminwong — COMMENTED** [review]
[PR81](https://github.com/anitab-org/bridge-in-tech-backend/pull/81) for [issue80](https://github.com/anitab-org/bridge-in-tech-backend/issues/80) was reviewed and tested. @mtreacy002 
review the following conflicting files when you have time 👍

**Comment by mtreacy002** [comment]
@ramitsawhney27 and @foongminwong, I've resolved the merged conflicts. I think you both need to re-approve it again as your previous approvals were removed by the force pushed.

**Review by ramitsawhney27 — DISMISSED** [review]

**Comment by foongminwong** [comment]
@mtreacy002 
When I tried to test `POST /user/personal_background` using the following input:
```json

{
  "gender": "MALE",
  "age": "DECLINED",
  "ethnicity": "DECLINED",
  "sexual_orientation": "DECLINED",
  "religion": "DECLINED",
  "physical_ability": "DECLINED",
  "mental_ability": "DECLINED",
  "socio_economic": "DECLINED",
  "highest_education": "DECLINED",
  "years_of_experience": "DECLINED",
  "gender_other": "DECLINED",
  "ethnicity_other": "NOT_APPLICABLE",
  "sexual_orientation_other": "DECLINED",
  "religion_other": "DECLINED",
  "physical_ability_other": "DECLINED",
  "mental_ability_other": "DECLINED",
  "socio_economic_other": "DECLINED",
  "highest_education_other": "DECLINED",
  "is_public": true
}
```

I got the following response:

test-pr-83-post-output

Do you know which `personal background fields input provided is/are not within the given list.`?

**Comment by mtreacy002** [comment]
@foongminwong .  As per our last week discussion on the enum logic all pushed to backend, the input fields now only take background  **VALUE** instead of their `Keys`. So, your input instead of `DECLINED` should be `Prefer not to say`. (Note: It's the same as POST. or PUT /user/additional_info where you give Timezone input in its enum value)
Note @anitab-org/bridgeintech-maintainers. I'll add this info in the API endpoint details so collaborator awaree of this.

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've just force pushed with the change on POST /user/personal_background doc string that Background enum input needs the enum VALUE. @ramitsawhney27 and @foongminwong , can you please re-approve? Thanks

**Review by ramitsawhney27 — APPROVED** [review]

**Review by foongminwong — APPROVED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses were tested as below:

   * _POST /user/personal_background_  
      _Screenshot/gif/url_:  

        test-pr-83-create-personal-bg-and-view


      _Description_: Above gif output shows users who added their personal background and viewed after that. 
      _Expected Result_:  As a user, I should be able to create my personal background.
      _Actual Result_: Same as expected
      _Json_:

```json
{
  "gender": "Prefer not to say",
  "age": "Prefer not to say",
  "ethnicity": "Prefer not to say",
  "sexual_orientation": "Prefer not to say",
  "religion": "Prefer not to say",
  "physical_ability": "Prefer not to say",
  "mental_ability": "Prefer not to say",
  "socio_economic": "Prefer not to say",
  "highest_education": "Prefer not to say",
  "years_of_experience": "Prefer not to say",
  "gender_other": "Prefer not to say",
  "ethnicity_other": "Prefer not to say",
  "sexual_orientation_other": "Prefer not to say",
  "religion_other": "Not Applicable",
  "physical_ability_other": "Not Applicable",
  "mental_ability_other": "Not Applicable",
  "socio_economic_other": "Not Applicable",
  "highest_education_other": "Not Applicable",
  "is_public": true
}
```


   * _GET /user/personal_background_  
      _Screenshot/gif/url_:  

       test-pr-83-no-personal-bg

      _Description_: Above gif output shows a person who does not have any personal background. 
      _Expected Result_:  As a user, I should be able to retrieve my personal background.
      _Actual Result_: Same as expected

3. OS Version: Windows 10

**Pull request merged**
