### PR TITLE
Test schema

### LINKED ISSUE #19: Start Backend Test Dev
## Description
As a student,
I need create and populate data models classes,
so that I can move on to the next tasks specified in the First Coding Phase Week 1.

## Mocks
N/A

### Update [Required]
- [ ] must have enough pip dependencies (aka requirements.txt) at least to start the app 
- [ ] must have remote server established as well as local server
- [ ] able to run project and see swagger UI 
- [ ] must have .env.template
- [ ] must have migration scripts for initial migration
- [ ] must have .gitignore, .pylintrc, and .travis.yml
- [ ] must have functions if user opted to create and populate UserModel, MentorshipRelationModel, TasksListModel, TaskCommentModel, UserExtensionModel, PersonalBackgroundModel, OrganizationModel, ProgramModel, MentorshipRelationExtensionModel
- [ ] must have basic tests setup e.g. test_config.py and other simple tests

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by all mentors.

## Estimation
2 days

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description

This branch is created to create MS and BIT schemas and populated them with mock data.
The list of dependencies needed are specified in the requirements.txt

Fixes #19 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
- Test was posted on issue#19 [comment](https://github.com/anitab-org/bridge-in-tech-backend/issues/19#issuecomment-630810898)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

**Additional Note**

Docker related file is still work-in-progress.

### CODE REVIEW

**Comment by mtreacy002** [comment]
Update: Just removed geoloc column in Organizations as it's no longer relevant, address is no longer compulsory field and squashed merge previous commits.

**Comment by meenakshi-dhanani** [comment]
This one commit has a lot of changes. Keep your commits small, please. eg. If you want to add docker related files, .dockerignore and Dockerfile, that is a separate task and should be in a separate commit as well.

**Comment by mtreacy002** [comment]
> This one commit has a lot of changes. Keep your commits small, please. eg. If you want to add docker related files, .dockerignore and Dockerfile, that is a separate task and should be in a separate commit as well.

I understand that the Dockerfile and .dockerignore file are not relevant to this commit and I can take it out if need to. But for the rest of the files, unfortunately, they are all needed to setup the initial database (including the migration script) and to populate the database with mock data using the add_mock_data() function. 😂  

I originally keep the commit separately in this PR as I went through steps (I had like 5 to 6 commits initially, one for each major steps, like basic flask setup, adding schemas, adding migration script etc). But as per discussed with mentors in 2:1 meeting last Sunday, we want to keep one PR to have one commit only, hence the squash commit was made 😉

**Comment by mtreacy002** [comment]
It probably also coz I was the one who created the issue and since I'm inexperience, I wasn't aware of the large scope it can get to. It'd help in the future if mentors can create small issues for me to work on so we won't have the same issue like this PR here... 😂

**Pull request closed without merging**
