### PR TITLE
fix: Token expiry check removed

### LINKED ISSUE #203: Bug: Token expiry no longer returned by MS backend
**Describe the bug**
Token expiry has been removed from the MS backend response when user login. This causes server crash since the BIT logic still checks for this token expiry when validating token. 

**To Reproduce**
1. Update your version of ms-backend-server by pulling the latest update from https://github.com/mtreacy002/mentorship-backend/tree/ms-backend-server.
It should include commit #1021 as the latest commit from MS backend
Screen Shot 2021-03-03 at 4 44 26 pm
 
2. Run ms-backend-server and bit backend server. 
3. Try to login from BIT Swagger UI, and see errror (see screenshot 1)
4. Go to terminal and see error (see screenshot 2)

**Expected behavior**
Once the token expiry check is removed from valid_token logic, user should be able to login. (see screenshot 4)

**Screenshots**
Screenshot 1 - Swagger UI error
Screen Shot 2021-03-03 at 4 48 24 pm

Screenshot 2 - Terminal error
Screen Shot 2021-03-03 at 4 53 46 pm

Screenshot 3 - The cause of error
Screen Shot 2021-03-03 at 4 55 06 pm

Screenshot 4 - Successful login once the token expiry check is removed
Screen Shot 2021-03-03 at 5 07 49 pm

**Desktop:**
 - OS: MacOS 
 - Browser: Chrome
 - Version: MacOS: Catalina v.10.15.7; Chrome: v88.0.4324.192 

**Additional context**
NA

### PR DESCRIPTION
**Pull request by 17sushmita**
### Description

Fixes #203 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

- Checked manually logging into BIT Swagger UI and error was resolved.
image
- Run tests by `python -m unittest discover tests` and all tests passed.
image

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@17sushmita , you can completely remove the 2 lines instead of commenting them out. I commented them in the issue description to show that those lines are not needed and will fix the bug once removed 😉.

**Comment by epicadk** [comment]
> @17sushmita , you can completely remove the 2 lines instead of commenting them out. I commented them in the issue description to show that those lines are not needed and will fix the bug once removed 😉.

We could also perform a check there to see if the token has expired or not. But I don't think that issue would remain beginner friendly.

**Comment by mtreacy002** [comment]
> > @17sushmita , you can completely remove the 2 lines instead of commenting them out. I commented them in the issue description to show that those lines are not needed and will fix the bug once removed 😉.
> 
> We could also perform a check there to see if the token has expired or not. But I don't think that issue would remain beginner friendly.

@epicadk , the reason behind removing these lines is because the token expiry has been removed from the [response body of login call](https://github.com/anitab-org/mentorship-backend/blob/develop/app/api/models/user.py) 😉
Screen Shot 2021-03-06 at 5 27 50 pm

**Comment by epicadk** [comment]
@mtreacy002 Yeah , but I was suggesting decoding the payload (which can be done without the signing key) and checking if the token has expired or not. If it has then returning a 401 response.

**Comment by mtreacy002** [comment]
> @mtreacy002 Yeah , but I was suggesting decoding the payload (which can be done without the signing key) and checking if the token has expired or not. If it has then returning a 401 response.

Would you like to open a separate issue for this then @epicadk? As you said above, it might be a bit more complex for first timers 😁

**Comment by epicadk** [comment]
> > @mtreacy002 Yeah , but I was suggesting decoding the payload (which can be done without the signing key) and checking if the token has expired or not. If it has then returning a 401 response.
> 
> Would you like to open a separate issue for this then @epicadk? As you said above, it might be a bit more complex for first timers 😁

Sure will do. 😄

**Comment by 17sushmita** [comment]
Should I make the requested changes or there is a new issue being opened?

**Comment by epicadk** [comment]
> Should I make the requested changes or there is a new issue being opened?

@17sushmita The issue has already been created. #206 I did want to work on it however I am currently busy with setting up docker so if you would like to work on it it's all yours : ).

**Comment by mtreacy002** [comment]
> > Should I make the requested changes or there is a new issue being opened?
> 
> @17sushmita The issue has already been created. #206 I did want to work on it however I am currently busy with setting up docker so if you would like to work on it it's all yours : ).

@17sushmita you can do the requested change here for now. The other issue opened by @epicadk can be tackle separately.

**Comment by epicadk** [comment]
> > > Should I make the requested changes or there is a new issue being opened?
> > 
> > 
> > @17sushmita The issue has already been created. #206 I did want to work on it however I am currently busy with setting up docker so if you would like to work on it it's all yours : ).
> 
> @17sushmita you can do the requested change here for now. The other issue opened by @epicadk can be tackle separately.

Oops sorry I thought you meant the changes I had suggested 😅. Yes please just remove the two commented lines and then the pr will be good to go : ).

**Review by epicadk — APPROVED** [review]

**Comment by epicadk** [comment]
LGTM 💯

**Review by mtreacy002 — APPROVED** [review]
Well done, @17sushmita for your work. Thank you for your contribution 🎉🎉

**Comment by epicadk** [comment]
> Well done, @17sushmita for your work. Thank you for your contribution 🎉🎉


Congratulations @17sushmita : ). 

@mtreacy002 Shouldn't we have tested it before?

**Comment by mtreacy002** [comment]
@epicadk, this fix (removing the 2 lines) was actually a result of my resolution after I found the bug on local machine, and I have shown the successful outcome after removing the lines on the issue #203 description (we can say the fix was tested beforehand 😁). 
So, as there are no other changes made, I don't think we need to test this again, plus @17sushmita also further emphasise this by providing screenshots in the "How this has been tested section".

**Comment by epicadk** [comment]
> @epicadk, this fix (removing the 2 lines) was actually a result of my resolution after I found the bug on local machine, and I have shown the successful outcome after removing the lines on the issue #203 description (we can say the fix was tested beforehand 😁).
> So, as there are no other changes made, I don't think we need to test this again, plus @17sushmita also further emphasise this by providing screenshots in the "How this has been tested section".

Oh okay 👍🏼

**Pull request merged**
