### PR TITLE
docs: updated setup instructions

### LINKED ISSUE #163: docs : Update setup instructions
## Description
As a contributor , 
I need the setup instructions upto date for all OS.

1)   .\env\Scripts\activate does not work for CMD as mentioned in instructions 
Soln : Remove entire paragraph and update to just 2 lines as the command is bound to 100% work
 ```
On Windows
For git bash users :  source ./venv/Scripts/activate
 For cmd users : venv\Scripts\activate
```
image

2) To maintain consistency in setup doc all commands in step 6 should be included in code blocks rather than it's current state 

3) Substep 1 and 2 of step 6 should include double quotes (" ") in stead of single quotes . Then only it works .
image

4) The output of  git remote -v  has minor changes update them
 and also add cd bridge-in-tech-backend before adding upstream otherwise a fatal error is received
image

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by vj-codes**
### Description

Updated instructions for Windows

Fixes #163

### Type of Change:

- Documentation

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vj-codes** [comment]
@mtreacy002 why is the build failing ? I haven't made any code changes also 🤔

**Comment by mtreacy002** [comment]
@vj-codes , Have you tried running the tests locally? Do the tests passed?

**Comment by mtreacy002** [comment]
Hi @vj-codes . I found the culprit of why the tests failed. I set the timestamp access expiry on the tests on Sep 30 (since I was aiming to the end of GSoC) which just passed 🤣 . So, I'll open an issue for that to change it to a further future date. 

Screen Shot 2020-10-02 at 8 02 55 am


Screen Shot 2020-10-02 at 7 59 04 am

**Comment by mtreacy002** [comment]
But I'll review this PR separately, as this is only doc change and has nothing to do with code base 😉

**Review by mtreacy002 — APPROVED** [review]
LGTM, @vj-codes . Thank you for your input. It'll be really helpful for those struggling to setup on windows machine (I'm included 😂). 🎉🎉🎉

**Comment by vj-codes** [comment]
@mtreacy002 thankss :)

**Pull request merged**
