### PR TITLE
Updated PULL_REQUEST_TEMPLATE.md

### LINKED ISSUE #193: Wrong information in pull request template
**Describe the bug**
In the pull request template , under checklist read last point -
`I have written Kotlin Docs whenever is applicable`
Bridge in tech does not use kotlin docs in either frontend or backend so that point should be removed.

**To Reproduce**
1. Go to 'PULL_REQUEST_TEMPLATE.md'
2. Scroll down to 'Checklist>>>Last point'
3. See error

**Expected behavior**
It shouldn't exist.

### PR DESCRIPTION
**Pull request by Debanitrkl**
Removed the Kotlin related checkpoint

### Description
Removed the Kotlin related checkpoint

Fixes #193 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Aaishpra — COMMENTED** [review]
@Debanitrkl, please remove irrelevant checklist points(under Code/QA assurance heading) from the PR description, and also checkmark the points that apply to your PR.
Other than this Great work 🎉

**Review by Rahulm2310 — APPROVED** [review]
LGTM 💯 . Cheers @Debanitrkl

**Review by Aaishpra — APPROVED** [review]
Thanks for your first contribution @Debanitrkl

**Comment by Rahulm2310** [comment]
@Debanitrkl  Try not to use develop branch for submitting a PR. You should always create a seperate branch when submitting a PR. I suggest you to go through the [Contribution Guidelines](https://github.com/anitab-org/bridge-in-tech-backend/blob/develop/.github/CONTRIBUTING.md). It would be great if you could close this PR and create a new PR using a seperate branch (not develop). Thanks 🙂

Cc: @mtreacy002

**Pull request closed without merging**
