### PR TITLE
Add missing images to BIT setup instructions Create main database sec…

### LINKED ISSUE #53: Doc: Add missing images to BIT setup instructions Create main database section
## Description
As a contributor,
I need to be able to see visual examples on how to setup my environment,
so that I can setup BridgeInTech backend development successfully.

## Mocks
The image below shows the missing images on [BIT Development Environment Setup Instructions](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup) wiki page.
Screen Shot 2020-06-14 at 10 38 02 pm

### Update [Required]
- [ ] provide the images described in the `TO DO` on the places shown on the image above. The changes is to be placed in the ENV_SETUP_INSTRUCTION.md inside .github folder (the first one below line 27 and the other below line 31 of the .md file).

### Enhancement to Update [Optional]
NA
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by VolatianaYuliana**
### Description

Add missing images to BIT setup instructions Create main database section:
- [x] supply image to show steps 1 and 2 command lines.
- [x] supply image to show steps 5 is confirmed.

Fixes https://github.com/anitab-org/bridge-in-tech-backend/issues/53

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@VolatianaYuliana , the Wiki Backend setup has reecently got updated. Can you please copy pasted those changes here and add your section 3 images on top of it? Thanks

**Comment by VolatianaYuliana** [comment]
@mtreacy002 I am not sure where those recent changes are. I am actually on the most recent commit. Can you please point me to those changes.

**Comment by mtreacy002** [comment]
> @mtreacy002 I am not sure where those recent changes are. I am actually on the most recent commit. Can you please point me to those changes.

Not to worry, @VolatianaYuliana. You don't neeed to update the content here, I'll adjusted myself once I approve and merge your PR (and one other PR about setup but on different section to your). Atm, no need for you to do anything else. I'll review your change now. Sorry for the false alarm. 😁

**Review by mtreacy002 — APPROVED** [review]
Good job on your First-Timers-Only issue, @VolatianaYuliana 🎉🎉. Thank you for contributing to the project. Look forward to your next contribution. 😉

**Comment by VolatianaYuliana** [comment]
My pleasure @mtreacy002 :)

**Review by Kajol-Kumari — APPROVED** [review]
Changes LGTM :+1:  @VolatianaYuliana Thank you for your contribution :)

**Pull request merged**
