### PR TITLE
chore: deployed documentation to gh pages

### LINKED ISSUE #234: [docs] Migrate docusaurus deployment from surge to gh-pages
### Is your feature request related to a problem? Please describe.
It will be better to have the docs on the github-pages.

### Describe the solution you'd like
Deploy the docs on gh-pages.
Take reference from this: anitab-org/mentorship-backend@4cc78ae

Time Required: 1 hour.

### PR DESCRIPTION
**Pull request by vj-codes**
### Description
added support for deploying documentation to Github pages

Fixes #234 

### Type of Change:

- Outreach
- Documentation

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by vj-codes** [comment]
The secrets will be either created by @mtreacy002 or the admins who have write access

**Comment by mtreacy002** [comment]
> The secrets will be either created by @mtreacy002 or the admins who have write access

@vj-codes , I don't think I have that level of access to the repo (creating secret key/variable). @isabelcosta , can you please help us with this? Thanks beforehand 😉

**Comment by isabelcosta** [comment]
I will add the github keys as I did for mentorship :) @mtreacy002

**Comment by isabelcosta** [comment]
I followed this https://github.com/anitab-org/mentorship-backend/pull/841#issuecomment-808741268 which I think should work

**Review by mtreacy002 — COMMENTED** [review]
@vj-codes , I changed the gh pages settings to below:
Screen Shot 2021-05-22 at 10 09 42 pm

But it shows a different readme to what we have on the repo. I could see the `Docusaurus 2` but, not the Docusaurus page, Is this intended?
Screen Shot 2021-05-22 at 10 09 09 pm

Also, I re-run gh workflow and still the deployment to gh page is skipped. @isabelcosta , do you have suggestion to why this happens?
Screen Shot 2021-05-22 at 10 15 00 pm

**Comment by mtreacy002** [comment]
Hi @vj-codes  and @isabelcosta . I've changed the deployed branch on the repo settings to `gh-pages` and re-run the workflow as you suggested in BIT Open Session last week so that the Docusaurus should be deployed properly. But I still see raw template of Docusaurus instead of the BIT backend Docusaurus like the one MS backend has. Do you know what went wrong here?
BIT backend repo gh-pages setting:
Screen Shot 2021-05-29 at 12 02 33 pm

What we can see on the deployed site (not-expected)
Screen Shot 2021-05-29 at 12 04 56 pm

What we would like to see (as per MS backend docusaurus)
Screen Shot 2021-05-29 at 12 06 44 pm

**Comment by mtreacy002** [comment]
PS: The deployment to gh-pages on the workflow still got skipped for some reason 🤔 
Screen Shot 2021-05-29 at 12 09 46 pm
cc @isabelcosta and @epicadk, can I have your thoughts on this, please?

**Comment by epicadk** [comment]
It's a pull request. If you have a look at the workflow it skips for pull requests.

**Comment by vj-codes** [comment]
@mtreacy002 after a bit of digging I found out that the content of `docusaurus.config.js` is a bit different here as compared to ms-backend.
For example, the top part on ms-backend `If you...` is part of the [config](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/docusaurus.config.js#L14) but absent on this repo 
TBH the home page for mentorship looks good so probably we can tweak the config here as well and the problemwould be fixed, what say? 👀

**Comment by mtreacy002** [comment]
> @mtreacy002 after a bit of digging I found out that the content of `docusaurus.config.js` is a bit different here as compared to ms-backend.
> For example, the top part on ms-backend `If you...` is part of the [config](https://github.com/anitab-org/mentorship-backend/blob/develop/docs/docusaurus.config.js#L14) but absent on this repo
> TBH the home page for mentorship looks good so probably we can tweak the config here as well and the problemwould be fixed, what say? 👀

That sounds like a good idea, @vj-codes .

**Comment by vj-codes** [comment]
Should it be done in this PR or will I need to create a separate issue for the same? @mtreacy002

**Comment by mtreacy002** [comment]
I think we can do it on this one, @vj-codes . Btw, as per @epicadk mentioned, the docusaurus deployment seems to only happens after we merge this PR, coz it won't be deployed from a pull request branch. I probably will approve and merge once you add the additional note you've suggested. Hope this ok 😉

**Review by mtreacy002 — APPROVED** [review]
Thank you @vj-codes for your work 🎉🎉🎉. I'll approve and merge this now since it'll only deploy once we merge this to develop branch. It doesn't seem to have other concerns at this stage 🤞.

**Comment by mtreacy002** [comment]
@isabelcosta and @epicadk , we still have issue with the deployment to gh-pages. The error seems to be related to the ssh key as per the screenshot below. Can you please help form your side?
Screen Shot 2021-06-13 at 8 36 01 pm

**Comment by vj-codes** [comment]
@mtreacy002 ran it locally, it looks similar to mentorship system.
The problem is with the secret key 👀 

Screenshot (29)

Screenshot (30)

**Comment by epicadk** [comment]
Busy with GSoC and college work. Assigning myself, I'll take a look when I'm free.

**Comment by mtreacy002** [comment]
> Busy with GSoC and college work. Assigning myself, I'll take a look when I'm free.

Thank you, @epicadk. Take your time, no rush. Just ping us when you have time to look at it 😉

**Comment by isabelcosta** [comment]
@mtreacy002 and @vj-codes so during the mentorship session, we figured out that I had the wrong SSH Key configured, it should have been the private one 😅 Now there is another little bug, easy to fix. @vj-codes will take care of it 💪🏾

**Pull request merged**
