### PR TITLE
Doc: Update ENV_SETUP_INTRUCTION.md to reflect wiki page update

### LINKED ISSUE #88: Dev: Update ENV_SETUP_INSTRUCTION.md to reflect the related wiki page changes
## Description
As a student,
I need update the ENV_SETUP_INSTRUCTION.md on `.github` folder,
so that I can make sure the file reflects the latest changes on its relevant [wiki page](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup).

## Mocks
NA

### Update [Required]
- [ ] the updated file content should be the same as the [BridgeInTech Development Setup Instructions](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup)

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
This PR update ENV_SETUP_INSTRUCTION.md to reflect the recent changes on [BIT dev environment setup wiki](https://github.com/anitab-org/bridge-in-tech-backend/wiki/BIT-development-environment-setup)

Fixes #88 

### Type of Change:
- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (new link to BIT dev env setup wiki link on readme file)

### How Has This Been Tested?
View the proposed .md on fork repo and confirm they show the expected content.
### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've updated the ENV_SETUP_INSTRUCTION.md to reflect the recent changes on BIT dev env setup instrunctions on wiki page. Please check it out. Ta

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers , This PR is needed as doc referred to in BIT backend dev env wiki and frontend README setup instructions. Please check and approve. Ta

**Review by foongminwong — DISMISSED** [review]
Tried to re-setup BIT backend locally with this updated docs which solves my schema error in [pr77](https://github.com/anitab-org/bridge-in-tech-backend/pull/77) 🎉

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . Need to add the MS-for-bit setup instructions as might be missing (just realized during troubleshoot with @foongminwong just now)

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . Added MS-for-BIT backend server setup instruction. This PR is now ready to merge.

**Review by foongminwong — APPROVED** [review]

**Review by isabelcosta — APPROVED** [review]

**Pull request merged**
