### PR TITLE
Feat: Issue#95 get users list for personal details api endpoint and tests

### LINKED ISSUE #95: Dev: GET /users list for personal details functionality
## Description
As a student,
I need to create GET /users/personal_details api endpoint,
so that I can give BIT users ability to get list of personal details of BIT members.

## Mocks
NA

### Update [Required]
- [ ] allow users to GET lists of users personal details

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
Allow user to get list of users'personal detail information

Fixes #95 

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Login as a user and send GET /users/personal_details by providing access token.

On successful request:
Screen Shot 2020-07-24 at 5 19 43 pm

On error response from invalid token:
Screen Shot 2020-07-24 at 8 48 43 pm

On internal server error:
Screen Shot 2020-07-24 at 10 22 27 pm

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've decided to do separate GET /users for personal_details, additional_info and personal background (just like how I did in GET /user profile). This PR is for getting list of users based on their personal details.

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . As discussed on BIT mentors meeting yesterday, I've decided to do get users list (GET /users) only for the personal details information. Once logged-in user get this list of users, if they want to get specific information of any users from the list, logged-in user can click on that particular user and send GET /users/{user_id}/<personal_details or additional_info or personal_background>. So, I'll close issue #97 since it's no longer relevant.

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've just pushed the latest code with changes  MS API endpoint request url from GET /users to GET/users/verified. Since users only need to see list of verified members in the `Members` page frontend, BIT will not need to see all registered users including the non-verified email members. The GET /users probably will be more suitable as Nice-to-have/Future feature as part of Admin functionality. 
This PR is now ready to be reviewed 😉

**Comment by mtreacy002** [comment]
**NOTE** @anitab-org/bridgeintech-maintainers. This PR also provides temporary fix to bug reported on issue #94. The fix is done through setting AUTH_COOKIE user_id to zero (0) everytime any users login to the system. This method fix the issue if the servers run on the local environment. This fix might not work on remote servers.

**Review by ramitsawhney27 — DISMISSED** [review]

**Review by foongminwong — DISMISSED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses were tested as below:

   * _Test PR 96 - Get userslist for personal details on BIT API_  
      _Screenshot/gif/url_:  

     test-bit-backend-pr-96-user-list


      _Expected Result_:  As a user, I should be able to retrieve users list on BIT backend API.
      _Actual Result_: Same as expected.

3. OS Version: Windows 10

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I've just resolved the merge conflict and force   pushed the changes. @ramitsawhney27 and @foongminwong , can you please ree-approve and mergee this PR when you have time? thanks

**Review by foongminwong — APPROVED** [review]

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I accidentally asked @ramitsawhney27 re-review and merge PR #99 which is blocked by this PR. But since that one already carry the code from this PR, when I pull rebase the recent merged develop branch to this PR, it automatically closed this PR. So, this ok, no code got lost in the process.

**Pull request closed without merging**
